#ifndef OP_PROTO_H_
#define OP_PROTO_H_

#include "graph/operator_reg.h"
#include "register/op_impl_registry.h"

namespace ge {

REG_OP(AddRelu)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(y, ge::TensorType::ALL())
    .OUTPUT(x, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(AddRelu);

REG_OP(AssignScoreWithk)
    .INPUT(points, ge::TensorType::ALL())
    .INPUT(centers, ge::TensorType::ALL())
    .INPUT(scores, ge::TensorType::ALL())
    .INPUT(knn_idx, ge::TensorType::ALL())
    .OUTPUT(output, ge::TensorType::ALL())
    .REQUIRED_ATTR(batch_size, Int)
    .REQUIRED_ATTR(nsource, Int)
    .REQUIRED_ATTR(npoint, Int)
    .REQUIRED_ATTR(num_weights, Int)
    .REQUIRED_ATTR(num_neighbors, Int)
    .REQUIRED_ATTR(num_features, Int)
    .REQUIRED_ATTR(aggregate, Int)
    .OP_END_FACTORY_REG(AssignScoreWithk);

REG_OP(AssignScoreWithkGrad)
    .INPUT(grad_out, ge::TensorType::ALL())
    .INPUT(points, ge::TensorType::ALL())
    .INPUT(centers, ge::TensorType::ALL())
    .INPUT(scores, ge::TensorType::ALL())
    .INPUT(knn_idx, ge::TensorType::ALL())
    .OUTPUT(grad_scores, ge::TensorType::ALL())
    .OUTPUT(grad_points, ge::TensorType::ALL())
    .OUTPUT(grad_centers, ge::TensorType::ALL())
    .REQUIRED_ATTR(batch_size, Int)
    .REQUIRED_ATTR(nsource, Int)
    .REQUIRED_ATTR(npoint, Int)
    .REQUIRED_ATTR(num_weights, Int)
    .REQUIRED_ATTR(num_neighbors, Int)
    .REQUIRED_ATTR(num_features, Int)
    .REQUIRED_ATTR(aggregate, Int)
    .OP_END_FACTORY_REG(AssignScoreWithkGrad);

REG_OP(BatchMatmulVector)
    .INPUT(projection_mat, ge::TensorType::ALL())
    .INPUT(pts_extend, ge::TensorType::ALL())
    .OUTPUT(point_2d, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(BatchMatmulVector);

REG_OP(BEVPool)
    .INPUT(feat, ge::TensorType::ALL())
    .INPUT(geom_feat, ge::TensorType::ALL())
    .INPUT(interval_lengths, ge::TensorType::ALL())
    .INPUT(interval_starts, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(b, Int)
    .REQUIRED_ATTR(d, Int)
    .REQUIRED_ATTR(h, Int)
    .REQUIRED_ATTR(w, Int)
    .REQUIRED_ATTR(c, Int)
    .OP_END_FACTORY_REG(BEVPool);

REG_OP(BEVPoolGrad)
    .INPUT(grad_out, ge::TensorType::ALL())
    .INPUT(geom_feat, ge::TensorType::ALL())
    .INPUT(interval_lengths, ge::TensorType::ALL())
    .INPUT(interval_starts, ge::TensorType::ALL())
    .OUTPUT(grad_feat, ge::TensorType::ALL())
    .REQUIRED_ATTR(b, Int)
    .REQUIRED_ATTR(d, Int)
    .REQUIRED_ATTR(h, Int)
    .REQUIRED_ATTR(w, Int)
    .REQUIRED_ATTR(c, Int)
    .OP_END_FACTORY_REG(BEVPoolGrad);

REG_OP(BEVPoolV2)
    .INPUT(depth, ge::TensorType::ALL())
    .INPUT(feat, ge::TensorType::ALL())
    .INPUT(ranks_depth, ge::TensorType::ALL())
    .INPUT(ranks_feat, ge::TensorType::ALL())
    .INPUT(ranks_bev, ge::TensorType::ALL())
    .INPUT(interval_lengths, ge::TensorType::ALL())
    .INPUT(interval_starts, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(b, Int)
    .REQUIRED_ATTR(d, Int)
    .REQUIRED_ATTR(h, Int)
    .REQUIRED_ATTR(w, Int)
    .REQUIRED_ATTR(c, Int)
    .OP_END_FACTORY_REG(BEVPoolV2);

REG_OP(BEVPoolV2Grad)
    .INPUT(grad_out, ge::TensorType::ALL())
    .INPUT(depth, ge::TensorType::ALL())
    .INPUT(feat, ge::TensorType::ALL())
    .INPUT(ranks_depth, ge::TensorType::ALL())
    .INPUT(ranks_feat, ge::TensorType::ALL())
    .INPUT(ranks_bev, ge::TensorType::ALL())
    .INPUT(interval_lengths, ge::TensorType::ALL())
    .INPUT(interval_starts, ge::TensorType::ALL())
    .OUTPUT(grad_depth, ge::TensorType::ALL())
    .OUTPUT(grad_feat, ge::TensorType::ALL())
    .REQUIRED_ATTR(b, Int)
    .REQUIRED_ATTR(d, Int)
    .REQUIRED_ATTR(h, Int)
    .REQUIRED_ATTR(w, Int)
    .REQUIRED_ATTR(c, Int)
    .OP_END_FACTORY_REG(BEVPoolV2Grad);

REG_OP(BEVPoolV3)
    .OPTIONAL_INPUT(depth, ge::TensorType::ALL())
    .INPUT(feat, ge::TensorType::ALL())
    .OPTIONAL_INPUT(ranks_depth, ge::TensorType::ALL())
    .OPTIONAL_INPUT(ranks_feat, ge::TensorType::ALL())
    .INPUT(ranks_bev, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(with_depth, Bool)
    .REQUIRED_ATTR(b, Int)
    .REQUIRED_ATTR(d, Int)
    .REQUIRED_ATTR(h, Int)
    .REQUIRED_ATTR(w, Int)
    .REQUIRED_ATTR(c, Int)
    .OP_END_FACTORY_REG(BEVPoolV3);

REG_OP(BEVPoolV3Grad)
    .INPUT(grad_out, ge::TensorType::ALL())
    .OPTIONAL_INPUT(depth, ge::TensorType::ALL())
    .INPUT(feat, ge::TensorType::ALL())
    .OPTIONAL_INPUT(ranks_depth, ge::TensorType::ALL())
    .OPTIONAL_INPUT(ranks_feat, ge::TensorType::ALL())
    .INPUT(ranks_bev, ge::TensorType::ALL())
    .OUTPUT(grad_depth, ge::TensorType::ALL())
    .OUTPUT(grad_feat, ge::TensorType::ALL())
    .REQUIRED_ATTR(with_depth, Bool)
    .OP_END_FACTORY_REG(BEVPoolV3Grad);

REG_OP(BorderAlign)
    .INPUT(input, ge::TensorType::ALL())
    .INPUT(rois, ge::TensorType::ALL())
    .OUTPUT(output, ge::TensorType::ALL())
    .REQUIRED_ATTR(pooledSize, Int)
    .OP_END_FACTORY_REG(BorderAlign);

REG_OP(BorderAlignGrad)
    .INPUT(gradOut, ge::TensorType::ALL())
    .INPUT(boxes, ge::TensorType::ALL())
    .INPUT(argmaxIdx, ge::TensorType::ALL())
    .OUTPUT(gradInput, ge::TensorType::ALL())
    .REQUIRED_ATTR(channels, Int)
    .REQUIRED_ATTR(boxSize, Int)
    .REQUIRED_ATTR(height, Int)
    .REQUIRED_ATTR(width, Int)
    .REQUIRED_ATTR(poolSize, Int)
    .REQUIRED_ATTR(batchSize, Int)
    .OP_END_FACTORY_REG(BorderAlignGrad);

REG_OP(BoxIou)
    .INPUT(boxes_a, ge::TensorType::ALL())
    .INPUT(boxes_b, ge::TensorType::ALL())
    .OUTPUT(ious, ge::TensorType::ALL())
    .ATTR(mode_flag, Int, 0)
    .ATTR(aligned, Bool, false)
    .OP_END_FACTORY_REG(BoxIou);

REG_OP(BoxesOverlapBev)
    .INPUT(boxes_a, ge::TensorType::ALL())
    .INPUT(boxes_b, ge::TensorType::ALL())
    .OUTPUT(res, ge::TensorType::ALL())
    .ATTR(format_flag, Int, 1)
    .ATTR(clockwise, Bool, true)
    .ATTR(mode_flag, Int, 0)
    .ATTR(aligned, Bool, false)
    .ATTR(margin, Float, 1e-05)
    .OP_END_FACTORY_REG(BoxesOverlapBev);

REG_OP(BoxesOverlapBevV1)
    .INPUT(boxes_a, ge::TensorType::ALL())
    .INPUT(boxes_b, ge::TensorType::ALL())
    .OUTPUT(res, ge::TensorType::ALL())
    .ATTR(format_flag, Int, 1)
    .ATTR(clockwise, Bool, true)
    .ATTR(mode_flag, Int, 0)
    .ATTR(aligned, Bool, false)
    .ATTR(margin, Float, 1e-05)
    .OP_END_FACTORY_REG(BoxesOverlapBevV1);

REG_OP(CalAnchorsHeading)
    .INPUT(anchors, ge::TensorType::ALL())
    .INPUT(origin_pos, ge::TensorType::ALL())
    .OUTPUT(heading, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(CalAnchorsHeading);

REG_OP(CalcPolyStartEndSl)
    .INPUT(min_idx, ge::TensorType::ALL())
    .INPUT(poly_line, ge::TensorType::ALL())
    .INPUT(points, ge::TensorType::ALL())
    .INPUT(s_cum, ge::TensorType::ALL())
    .OUTPUT(poly_start, ge::TensorType::ALL())
    .OUTPUT(poly_end, ge::TensorType::ALL())
    .OUTPUT(sl, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(CalcPolyStartEndSl);

REG_OP(CartesianToFrenet1)
    .INPUT(dist_vec, ge::TensorType::ALL())
    .OUTPUT(min_idx, ge::TensorType::ALL())
    .OUTPUT(back_idx, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(CartesianToFrenet1);

REG_OP(CylinderQuery)
    .INPUT(new_xyz, ge::TensorType::ALL())
    .INPUT(xyz, ge::TensorType::ALL())
    .INPUT(rot, ge::TensorType::ALL())
    .INPUT(origin_index, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(batch_size, Int)
    .REQUIRED_ATTR(point_cloud_size, Int)
    .REQUIRED_ATTR(query_point_size, Int)
    .REQUIRED_ATTR(radius, Float)
    .REQUIRED_ATTR(hmin, Float)
    .REQUIRED_ATTR(hmax, Float)
    .REQUIRED_ATTR(nsample, Int)
    .OP_END_FACTORY_REG(CylinderQuery);

REG_OP(DeformableAggregation)
    .INPUT(mc_ms_feat, ge::TensorType::ALL())
    .INPUT(spatial_shape, ge::TensorType::ALL())
    .INPUT(scale_start_index, ge::TensorType::ALL())
    .INPUT(sampling_location, ge::TensorType::ALL())
    .INPUT(weights, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(batch_size, Int)
    .REQUIRED_ATTR(num_feat, Int)
    .REQUIRED_ATTR(num_embeds, Int)
    .REQUIRED_ATTR(num_anchors, Int)
    .REQUIRED_ATTR(num_pts, Int)
    .REQUIRED_ATTR(num_cams, Int)
    .REQUIRED_ATTR(num_scale, Int)
    .REQUIRED_ATTR(num_groups, Int)
    .OP_END_FACTORY_REG(DeformableAggregation);

REG_OP(DeformableAggregationGrad)
    .INPUT(mc_ms_feat, ge::TensorType::ALL())
    .INPUT(spatial_shape, ge::TensorType::ALL())
    .INPUT(scale_start_index, ge::TensorType::ALL())
    .INPUT(sampling_location, ge::TensorType::ALL())
    .INPUT(weights, ge::TensorType::ALL())
    .INPUT(grad_output, ge::TensorType::ALL())
    .OUTPUT(grad_mc_ms_feat, ge::TensorType::ALL())
    .OUTPUT(grad_sampling_location, ge::TensorType::ALL())
    .OUTPUT(grad_weights, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(DeformableAggregationGrad);

REG_OP(DeformableConv2d)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .OPTIONAL_INPUT(bias, ge::TensorType::ALL())
    .INPUT(offset, ge::TensorType::ALL())
    .OPTIONAL_INPUT(mask, ge::TensorType::ALL())
    .OUTPUT(y, ge::TensorType::ALL())
    .OUTPUT(offset_output, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(stride, ListInt)
    .REQUIRED_ATTR(padding, ListInt)
    .REQUIRED_ATTR(dilation, ListInt)
    .REQUIRED_ATTR(groups, Int)
    .REQUIRED_ATTR(deformable_groups, Int)
    .REQUIRED_ATTR(modulated, Bool)
    .REQUIRED_ATTR(with_bias, Bool)
    .OP_END_FACTORY_REG(DeformableConv2d);

REG_OP(DeformableConv2dGrad)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .OPTIONAL_INPUT(bias, ge::TensorType::ALL())
    .INPUT(offset, ge::TensorType::ALL())
    .OPTIONAL_INPUT(mask, ge::TensorType::ALL())
    .INPUT(offset_output, ge::TensorType::ALL())
    .INPUT(grad_y, ge::TensorType::ALL())
    .OUTPUT(grad_x, ge::TensorType::ALL())
    .OUTPUT(grad_weight, ge::TensorType::ALL())
    .OUTPUT(grad_bias, ge::TensorType::ALL())
    .OUTPUT(grad_offset, ge::TensorType::ALL())
    .OUTPUT(grad_mask, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(stride, ListInt)
    .REQUIRED_ATTR(padding, ListInt)
    .REQUIRED_ATTR(dilation, ListInt)
    .REQUIRED_ATTR(groups, Int)
    .REQUIRED_ATTR(deformable_groups, Int)
    .REQUIRED_ATTR(modulated, Bool)
    .REQUIRED_ATTR(with_bias, Bool)
    .OP_END_FACTORY_REG(DeformableConv2dGrad);

REG_OP(DeformableConv2dGradV2)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .OPTIONAL_INPUT(bias, ge::TensorType::ALL())
    .INPUT(offset, ge::TensorType::ALL())
    .OPTIONAL_INPUT(mask, ge::TensorType::ALL())
    .INPUT(grad_y, ge::TensorType::ALL())
    .OUTPUT(grad_x, ge::TensorType::ALL())
    .OUTPUT(grad_weight, ge::TensorType::ALL())
    .OUTPUT(grad_bias, ge::TensorType::ALL())
    .OUTPUT(grad_offset, ge::TensorType::ALL())
    .OUTPUT(grad_mask, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(stride, ListInt)
    .REQUIRED_ATTR(padding, ListInt)
    .REQUIRED_ATTR(dilation, ListInt)
    .REQUIRED_ATTR(groups, Int)
    .REQUIRED_ATTR(deformable_groups, Int)
    .REQUIRED_ATTR(modulated, Bool)
    .REQUIRED_ATTR(with_bias, Bool)
    .OP_END_FACTORY_REG(DeformableConv2dGradV2);

REG_OP(DeformableConv2dV2)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(offset, ge::TensorType::ALL())
    .OPTIONAL_INPUT(mask, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .OPTIONAL_INPUT(bias, ge::TensorType::ALL())
    .OUTPUT(y, ge::TensorType::ALL())
    .OUTPUT(offset_output, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(stride, ListInt)
    .REQUIRED_ATTR(padding, ListInt)
    .REQUIRED_ATTR(dilation, ListInt)
    .REQUIRED_ATTR(groups, Int)
    .REQUIRED_ATTR(deformable_groups, Int)
    .REQUIRED_ATTR(modulated, Bool)
    .REQUIRED_ATTR(with_bias, Bool)
    .OP_END_FACTORY_REG(DeformableConv2dV2);

REG_OP(DiffIouRotatedSortVertices)
    .INPUT(vertices, ge::TensorType::ALL())
    .INPUT(mask, ge::TensorType::ALL())
    .INPUT(num_valid, ge::TensorType::ALL())
    .OUTPUT(sortedIdx, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(DiffIouRotatedSortVertices);

REG_OP(DrawGaussianToHeatmap)
    .INPUT(mask, ge::TensorType::ALL())
    .INPUT(cur_class_id, ge::TensorType::ALL())
    .INPUT(center_int, ge::TensorType::ALL())
    .INPUT(radius, ge::TensorType::ALL())
    .OUTPUT(heatmap, ge::TensorType::ALL())
    .REQUIRED_ATTR(num_classes, Int)
    .REQUIRED_ATTR(feature_map_size_x, Int)
    .REQUIRED_ATTR(feature_map_size_y, Int)
    .OP_END_FACTORY_REG(DrawGaussianToHeatmap);

REG_OP(DynamicScatter)
    .INPUT(feats, ge::TensorType::ALL())
    .INPUT(prefix_sum_point_per_voxel, ge::TensorType::ALL())
    .INPUT(argsort_coor, ge::TensorType::ALL())
    .OUTPUT(voxel_feats, ge::TensorType::ALL())
    .OUTPUT(compare_mask, ge::TensorType::ALL())
    .REQUIRED_ATTR(reduce_type, String)
    .OP_END_FACTORY_REG(DynamicScatter);

REG_OP(DynamicScatterGrad)
    .INPUT(grad_voxel_feats, ge::TensorType::ALL())
    .INPUT(num_point_per_voxel, ge::TensorType::ALL())
    .INPUT(argsort_coor, ge::TensorType::ALL())
    .INPUT(compare_mask, ge::TensorType::ALL())
    .OUTPUT(grad_feats, ge::TensorType::ALL())
    .REQUIRED_ATTR(reduce_type, String)
    .OP_END_FACTORY_REG(DynamicScatterGrad);

REG_OP(DynamicVoxelization)
    .INPUT(points, ge::TensorType::ALL())
    .OUTPUT(coors, ge::TensorType::ALL())
    .REQUIRED_ATTR(coors_min_x, Float)
    .REQUIRED_ATTR(coors_min_y, Float)
    .REQUIRED_ATTR(coors_min_z, Float)
    .REQUIRED_ATTR(voxel_x, Float)
    .REQUIRED_ATTR(voxel_y, Float)
    .REQUIRED_ATTR(voxel_z, Float)
    .REQUIRED_ATTR(grid_x, Int)
    .REQUIRED_ATTR(grid_y, Int)
    .REQUIRED_ATTR(grid_z, Int)
    .OP_END_FACTORY_REG(DynamicVoxelization);

REG_OP(FakeTensorQuant)
    .INPUT(inputs, ge::TensorType::ALL())
    .INPUT(amax, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(num_bits, Int)
    .REQUIRED_ATTR(is_unsigned, Bool)
    .REQUIRED_ATTR(narrow_range, Bool)
    .OP_END_FACTORY_REG(FakeTensorQuant);

REG_OP(FakeTensorQuantWithAxis)
    .INPUT(inputs, ge::TensorType::ALL())
    .INPUT(amax, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(axis, Int)
    .REQUIRED_ATTR(num_bits, Int)
    .REQUIRED_ATTR(is_unsigned, Bool)
    .REQUIRED_ATTR(narrow_range, Bool)
    .OP_END_FACTORY_REG(FakeTensorQuantWithAxis);

REG_OP(FurthestPointSampling)
    .INPUT(point_xyz, ge::TensorType::ALL())
    .INPUT(nearest_temp, ge::TensorType::ALL())
    .OUTPUT(index, ge::TensorType::ALL())
    .REQUIRED_ATTR(num_points, Int)
    .OP_END_FACTORY_REG(FurthestPointSampling);

REG_OP(FurthestPointSamplingWithDist)
    .INPUT(points_dist, ge::TensorType::ALL())
    .INPUT(nearest_temp, ge::TensorType::ALL())
    .OUTPUT(index, ge::TensorType::ALL())
    .REQUIRED_ATTR(num_points, Int)
    .OP_END_FACTORY_REG(FurthestPointSamplingWithDist);

REG_OP(FusedBiasLeakyReluV2)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(bias, ge::TensorType::ALL())
    .OUTPUT(output, ge::TensorType::ALL())
    .REQUIRED_ATTR(negative_slope, Float)
    .REQUIRED_ATTR(scale, Float)
    .OP_END_FACTORY_REG(FusedBiasLeakyReluV2);

REG_OP(GatherNms3dMask)
    .INPUT(mask, ge::TensorType::ALL())
    .OUTPUT(keep, ge::TensorType::ALL())
    .OUTPUT(num_out, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(GatherNms3dMask);

REG_OP(Gaussian)
    .INPUT(gt_boxes, ge::TensorType::ALL())
    .OUTPUT(center_int, ge::TensorType::ALL())
    .OUTPUT(radius, ge::TensorType::ALL())
    .OUTPUT(mask, ge::TensorType::ALL())
    .OUTPUT(ind, ge::TensorType::ALL())
    .OUTPUT(ret_boxes, ge::TensorType::ALL())
    .REQUIRED_ATTR(feature_map_stride, Int)
    .REQUIRED_ATTR(gaussian_overlap, Float)
    .REQUIRED_ATTR(min_radius, Int)
    .REQUIRED_ATTR(num_max_objs, Int)
    .REQUIRED_ATTR(voxel_size_x, Float)
    .REQUIRED_ATTR(voxel_size_y, Float)
    .REQUIRED_ATTR(pc_range_x, Float)
    .REQUIRED_ATTR(pc_range_y, Float)
    .REQUIRED_ATTR(feature_map_size_x, Int)
    .REQUIRED_ATTR(feature_map_size_y, Int)
    .REQUIRED_ATTR(norm_bbox, Bool)
    .REQUIRED_ATTR(flip_angle, Bool)
    .OP_END_FACTORY_REG(Gaussian);

REG_OP(GeometricKernelAttention)
    .INPUT(value, ge::TensorType::ALL())
    .INPUT(spatial_shapes, ge::TensorType::ALL())
    .INPUT(level_start_index, ge::TensorType::ALL())
    .INPUT(sampling_locations, ge::TensorType::ALL())
    .INPUT(attention_weights, ge::TensorType::ALL())
    .OUTPUT(output, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(GeometricKernelAttention);

REG_OP(GeometricKernelAttnGrad)
    .INPUT(value, ge::TensorType::ALL())
    .INPUT(spatial_shapes, ge::TensorType::ALL())
    .INPUT(level_start_index, ge::TensorType::ALL())
    .INPUT(sampling_locations, ge::TensorType::ALL())
    .INPUT(attn_weights, ge::TensorType::ALL())
    .INPUT(grad_output, ge::TensorType::ALL())
    .OUTPUT(grad_value, ge::TensorType::ALL())
    .OUTPUT(grad_attn_weights, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(GeometricKernelAttnGrad);

REG_OP(GraphSoftmax)
    .INPUT(src, ge::TensorType::ALL())
    .INPUT(index, ge::TensorType::ALL())
    .OUTPUT(softmax_result, ge::TensorType::ALL())
    .REQUIRED_ATTR(N, Int)
    .OP_END_FACTORY_REG(GraphSoftmax);

REG_OP(GraphSoftmaxGrad)
    .INPUT(index, ge::TensorType::ALL())
    .INPUT(softmax_output, ge::TensorType::ALL())
    .INPUT(grad_output, ge::TensorType::ALL())
    .INPUT(reduce_sum, ge::TensorType::ALL())
    .OUTPUT(src_grad, ge::TensorType::ALL())
    .REQUIRED_ATTR(node_num, Int)
    .OP_END_FACTORY_REG(GraphSoftmaxGrad);

REG_OP(GridSampler2dV2)
    .INPUT(x_trans, ge::TensorType::ALL())
    .INPUT(grid, ge::TensorType::ALL())
    .OUTPUT(y_trans, ge::TensorType::ALL())
    .REQUIRED_ATTR(interpolation_mode, Int)
    .REQUIRED_ATTR(padding_mode, Int)
    .REQUIRED_ATTR(align_corners, Bool)
    .OP_END_FACTORY_REG(GridSampler2dV2);

REG_OP(GridSampler2dV2Grad)
    .INPUT(grad, ge::TensorType::ALL())
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(grid, ge::TensorType::ALL())
    .OUTPUT(dx, ge::TensorType::ALL())
    .OUTPUT(dgrid, ge::TensorType::ALL())
    .REQUIRED_ATTR(interpolation_mode, Int)
    .REQUIRED_ATTR(padding_mode, Int)
    .REQUIRED_ATTR(align_corners, Bool)
    .OP_END_FACTORY_REG(GridSampler2dV2Grad);

REG_OP(GridSampler3dGradV1)
    .INPUT(grad, ge::TensorType::ALL())
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(grid, ge::TensorType::ALL())
    .OUTPUT(dx, ge::TensorType::ALL())
    .OUTPUT(dgrid, ge::TensorType::ALL())
    .REQUIRED_ATTR(interpolation_mode, Int)
    .REQUIRED_ATTR(padding_mode, Int)
    .REQUIRED_ATTR(align_corners, Bool)
    .OP_END_FACTORY_REG(GridSampler3dGradV1);

REG_OP(GroupPoints)
    .INPUT(points, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(b, Int)
    .REQUIRED_ATTR(c, Int)
    .REQUIRED_ATTR(n, Int)
    .REQUIRED_ATTR(npoints, Int)
    .REQUIRED_ATTR(nsample, Int)
    .OP_END_FACTORY_REG(GroupPoints);

REG_OP(GroupPointsGrad)
    .INPUT(grad_out, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .OUTPUT(grad_points, ge::TensorType::ALL())
    .REQUIRED_ATTR(b, Int)
    .REQUIRED_ATTR(c, Int)
    .REQUIRED_ATTR(n, Int)
    .REQUIRED_ATTR(npoints, Int)
    .REQUIRED_ATTR(nsample, Int)
    .OP_END_FACTORY_REG(GroupPointsGrad);

REG_OP(HardVoxelize)
    .INPUT(points, ge::TensorType::ALL())
    .INPUT(uni_voxels, ge::TensorType::ALL())
    .INPUT(argsort_voxel_idices, ge::TensorType::ALL())
    .INPUT(uni_argsort_idices, ge::TensorType::ALL())
    .INPUT(uni_indices, ge::TensorType::ALL())
    .OUTPUT(voxels, ge::TensorType::ALL())
    .OUTPUT(num_points_per_voxel, ge::TensorType::ALL())
    .OUTPUT(sorted_uni_voxels, ge::TensorType::ALL())
    .REQUIRED_ATTR(num_voxels, Int)
    .REQUIRED_ATTR(max_voxels, Int)
    .REQUIRED_ATTR(max_points, Int)
    .REQUIRED_ATTR(num_points, Int)
    .OP_END_FACTORY_REG(HardVoxelize);

REG_OP(Hypot)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(y, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(Hypot);

REG_OP(HypotGrad)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(y, ge::TensorType::ALL())
    .INPUT(z, ge::TensorType::ALL())
    .INPUT(z_grad, ge::TensorType::ALL())
    .OUTPUT(x_grad, ge::TensorType::ALL())
    .OUTPUT(y_grad, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(HypotGrad);

REG_OP(Knn)
    .INPUT(xyz, ge::TensorType::ALL())
    .INPUT(center_xyz, ge::TensorType::ALL())
    .OUTPUT(dist, ge::TensorType::ALL())
    .OUTPUT(idx, ge::TensorType::ALL())
    .REQUIRED_ATTR(is_from_knn, Bool)
    .REQUIRED_ATTR(k, Int)
    .OP_END_FACTORY_REG(Knn);

REG_OP(MaxPool2d)
    .INPUT(x_trans, ge::TensorType::ALL())
    .OUTPUT(y_trans, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(MaxPool2d);

REG_OP(MultiScaleDeformableAttn)
    .INPUT(value, ge::TensorType::ALL())
    .INPUT(value_spatial_shapes, ge::TensorType::ALL())
    .INPUT(value_level_start_index, ge::TensorType::ALL())
    .INPUT(sampling_locations, ge::TensorType::ALL())
    .INPUT(attention_weights, ge::TensorType::ALL())
    .OUTPUT(output, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(MultiScaleDeformableAttn);

REG_OP(MultiScaleDeformableAttnGrad)
    .INPUT(value, ge::TensorType::ALL())
    .INPUT(spatial_shapes, ge::TensorType::ALL())
    .INPUT(level_start_index, ge::TensorType::ALL())
    .INPUT(sampling_loc, ge::TensorType::ALL())
    .INPUT(attn_weight, ge::TensorType::ALL())
    .INPUT(grad_output, ge::TensorType::ALL())
    .OUTPUT(grad_value, ge::TensorType::ALL())
    .OUTPUT(grad_sampling_loc, ge::TensorType::ALL())
    .OUTPUT(grad_attn_weight, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(MultiScaleDeformableAttnGrad);

REG_OP(Nms3d)
    .INPUT(boxes, ge::TensorType::ALL())
    .OUTPUT(mask, ge::TensorType::ALL())
    .REQUIRED_ATTR(threshold, Float)
    .OP_END_FACTORY_REG(Nms3d);

REG_OP(Nms3dNormal)
    .INPUT(boxes, ge::TensorType::ALL())
    .OUTPUT(mask, ge::TensorType::ALL())
    .REQUIRED_ATTR(nms_overlap_thresh, Float)
    .OP_END_FACTORY_REG(Nms3dNormal);

REG_OP(Nms3dOnSight)
    .INPUT(boxes, ge::TensorType::ALL())
    .OUTPUT(mask, ge::TensorType::ALL())
    .REQUIRED_ATTR(threshold, Float)
    .OP_END_FACTORY_REG(Nms3dOnSight);

REG_OP(PixelGroup)
    .INPUT(score, ge::TensorType::ALL())
    .INPUT(mask, ge::TensorType::ALL())
    .INPUT(embedding, ge::TensorType::ALL())
    .INPUT(kernel_label, ge::TensorType::ALL())
    .INPUT(kernel_contour, ge::TensorType::ALL())
    .OUTPUT(point_vector, ge::TensorType::ALL())
    .OUTPUT(label_updated, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_region_num, Int)
    .REQUIRED_ATTR(distance_threshold, Float)
    .OP_END_FACTORY_REG(PixelGroup);

REG_OP(PointToVoxel)
    .INPUT(points, ge::TensorType::ALL())
    .OUTPUT(voxels, ge::TensorType::ALL())
    .REQUIRED_ATTR(voxel_sizes, ListFloat)
    .REQUIRED_ATTR(coor_ranges, ListFloat)
    .REQUIRED_ATTR(layout, String)
    .OP_END_FACTORY_REG(PointToVoxel);

REG_OP(VoxelToPoint)
    .INPUT(voxels, ge::TensorType::ALL())
    .OUTPUT(points, ge::TensorType::ALL())
    .REQUIRED_ATTR(voxel_sizes, ListFloat)
    .REQUIRED_ATTR(coor_ranges, ListFloat)
    .REQUIRED_ATTR(layout, String)
    .OP_END_FACTORY_REG(VoxelToPoint);

REG_OP(PointsInBox)
    .INPUT(boxes, ge::TensorType::ALL())
    .INPUT(pts, ge::TensorType::ALL())
    .OUTPUT(boxes_idx_of_points, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(PointsInBox);

REG_OP(PointsInBoxAll)
    .INPUT(boxes, ge::TensorType::ALL())
    .INPUT(pts, ge::TensorType::ALL())
    .OUTPUT(boxes_idx_of_points, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(PointsInBoxAll);

REG_OP(Radius)
    .INPUT(x, ge::TensorType::ALL())
    .INPUT(y, ge::TensorType::ALL())
    .INPUT(ptr_x, ge::TensorType::ALL())
    .INPUT(ptr_y, ge::TensorType::ALL())
    .OUTPUT(out_temp, ge::TensorType::ALL())
    .OUTPUT(out_final, ge::TensorType::ALL())
    .OUTPUT(actual_num_neighbors, ge::TensorType::ALL())
    .REQUIRED_ATTR(r, Float)
    .REQUIRED_ATTR(max_num_neighbors, Int)
    .OP_END_FACTORY_REG(Radius);

REG_OP(RoiAlignRotatedGradV2)
    .INPUT(input, ge::TensorType::ALL())
    .INPUT(rois, ge::TensorType::ALL())
    .INPUT(grad_output, ge::TensorType::ALL())
    .OUTPUT(grad_input, ge::TensorType::ALL())
    .REQUIRED_ATTR(pooled_height, Int)
    .REQUIRED_ATTR(pooled_width, Int)
    .REQUIRED_ATTR(spatial_scale, Float)
    .REQUIRED_ATTR(sampling_ratio, Int)
    .REQUIRED_ATTR(aligned, Bool)
    .REQUIRED_ATTR(clockwise, Bool)
    .OP_END_FACTORY_REG(RoiAlignRotatedGradV2);

REG_OP(RoiAlignRotatedV2)
    .INPUT(input, ge::TensorType::ALL())
    .INPUT(rois, ge::TensorType::ALL())
    .OUTPUT(output, ge::TensorType::ALL())
    .REQUIRED_ATTR(spatial_scale, Float)
    .REQUIRED_ATTR(sampling_ratio, Int)
    .REQUIRED_ATTR(pooled_height, Int)
    .REQUIRED_ATTR(pooled_width, Int)
    .REQUIRED_ATTR(aligned, Bool)
    .REQUIRED_ATTR(clockwise, Bool)
    .OP_END_FACTORY_REG(RoiAlignRotatedV2);

REG_OP(RoiawareAvgpool3dGrad)
    .INPUT(pts_idx_of_voxels, ge::TensorType::ALL())
    .INPUT(grad_out, ge::TensorType::ALL())
    .OUTPUT(grad_in, ge::TensorType::ALL())
    .REQUIRED_ATTR(boxes_num, Int)
    .REQUIRED_ATTR(out_x, Int)
    .REQUIRED_ATTR(out_y, Int)
    .REQUIRED_ATTR(out_z, Int)
    .REQUIRED_ATTR(channels, Int)
    .REQUIRED_ATTR(npoints, Int)
    .REQUIRED_ATTR(max_pts_per_voxel, Int)
    .OP_END_FACTORY_REG(RoiawareAvgpool3dGrad);

REG_OP(RoiawareMaxpool3dGrad)
    .INPUT(argmax, ge::TensorType::ALL())
    .INPUT(grad_out, ge::TensorType::ALL())
    .OUTPUT(grad_in, ge::TensorType::ALL())
    .REQUIRED_ATTR(boxes_num, Int)
    .REQUIRED_ATTR(out_x, Int)
    .REQUIRED_ATTR(out_y, Int)
    .REQUIRED_ATTR(out_z, Int)
    .REQUIRED_ATTR(channels, Int)
    .REQUIRED_ATTR(npoints, Int)
    .OP_END_FACTORY_REG(RoiawareMaxpool3dGrad);

REG_OP(RoiawarePool3d)
    .INPUT(rois, ge::TensorType::ALL())
    .INPUT(pts, ge::TensorType::ALL())
    .INPUT(pts_feature, ge::TensorType::ALL())
    .OUTPUT(argmax, ge::TensorType::ALL())
    .OUTPUT(pts_idx_of_voxels, ge::TensorType::ALL())
    .OUTPUT(pooled_features, ge::TensorType::ALL())
    .REQUIRED_ATTR(mode, Int)
    .REQUIRED_ATTR(max_pts_each_voxel, Int)
    .REQUIRED_ATTR(outx, Int)
    .REQUIRED_ATTR(outy, Int)
    .REQUIRED_ATTR(outz, Int)
    .OP_END_FACTORY_REG(RoiawarePool3d);

REG_OP(RoipointPool3dForward)
    .INPUT(points, ge::TensorType::ALL())
    .INPUT(point_features, ge::TensorType::ALL())
    .INPUT(boxes3d, ge::TensorType::ALL())
    .OUTPUT(pooled_features, ge::TensorType::ALL())
    .OUTPUT(pooled_empty_flag, ge::TensorType::ALL())
    .ATTR(num_sampled_points, Int, 0)
    .OP_END_FACTORY_REG(RoipointPool3dForward);

REG_OP(ScatterAddGradV1)
    .INPUT(grad_out, ge::TensorType::ALL())
    .INPUT(index, ge::TensorType::ALL())
    .OUTPUT(grad_in, ge::TensorType::ALL())
    .REQUIRED_ATTR(dim, Int)
    .OP_END_FACTORY_REG(ScatterAddGradV1);

REG_OP(ScatterAddV1)
    .INPUT(src, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .INPUT(var, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .REQUIRED_ATTR(dim, Int)
    .OP_END_FACTORY_REG(ScatterAddV1);

REG_OP(ScatterMaxV1)
    .INPUT(src, ge::TensorType::ALL())
    .INPUT(index, ge::TensorType::ALL())
    .OUTPUT(res, ge::TensorType::ALL())
    .OUTPUT(argmax, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(ScatterMaxV1);

REG_OP(ScatterMaxArgmaxV1)
    .INPUT(src, ge::TensorType::ALL())
    .INPUT(index, ge::TensorType::ALL())
    .OUTPUT(res, ge::TensorType::ALL())
    .OUTPUT(argmax, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(ScatterMaxArgmaxV1);

REG_OP(ScatterMean)
    .INPUT(src, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .INPUT(var, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .OUTPUT(count, ge::TensorType::ALL())
    .REQUIRED_ATTR(dim, Int)
    .OP_END_FACTORY_REG(ScatterMean);

REG_OP(ScatterMeanDiv)
    .INPUT(src, ge::TensorType::ALL())
    .INPUT(count, ge::TensorType::ALL())
    .OUTPUT(out, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(ScatterMeanDiv);

REG_OP(ScatterMeanGrad)
    .INPUT(grad_out, ge::TensorType::ALL())
    .INPUT(index, ge::TensorType::ALL())
    .INPUT(count, ge::TensorType::ALL())
    .OUTPUT(grad_in, ge::TensorType::ALL())
    .REQUIRED_ATTR(dim, Int)
    .OP_END_FACTORY_REG(ScatterMeanGrad);

REG_OP(SelectIdxWithMask)
    .INPUT(poly_line, ge::TensorType::ALL())
    .INPUT(min_idx, ge::TensorType::ALL())
    .INPUT(pt, ge::TensorType::ALL())
    .INPUT(back_idx, ge::TensorType::ALL())
    .OUTPUT(out_min_idx, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(SelectIdxWithMask);

REG_OP(SparseConv3d)
    .INPUT(indices, ge::TensorType::ALL())
    .OUTPUT(indices_out, ge::TensorType::ALL())
    .OUTPUT(indices_pair, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(out_spatial_shape, ListInt)
    .REQUIRED_ATTR(stride, ListInt)
    .REQUIRED_ATTR(padding, ListInt)
    .OP_END_FACTORY_REG(SparseConv3d);

REG_OP(SparseConv3dGrad)
    .INPUT(features, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .OPTIONAL_INPUT(grad_out_features, ge::TensorType::ALL())
    .INPUT(former_sorted_indices, ge::TensorType::ALL())
    .INPUT(indices_offset, ge::TensorType::ALL())
    .OUTPUT(features_grad, ge::TensorType::ALL())
    .OUTPUT(weight_grad, ge::TensorType::ALL())
    .REQUIRED_ATTR(start_offset, Int)
    .REQUIRED_ATTR(end_offset, Int)
    .OP_END_FACTORY_REG(SparseConv3dGrad);

REG_OP(SparseInverseConv3d)
    .INPUT(features, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .INPUT(unique_indices_offset, ge::TensorType::ALL())
    .INPUT(sorted_idx_to_former_indices, ge::TensorType::ALL())
    .OUTPUT(output_img2col, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(in_channels, Int)
    .OP_END_FACTORY_REG(SparseInverseConv3d);

REG_OP(SparseMatmul)
    .INPUT(features, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .INPUT(unique_indices_offset, ge::TensorType::ALL())
    .INPUT(former_sorted_indices, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .OUTPUT(sparse_value, ge::TensorType::ALL())
    .OUTPUT(sparse_indices, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(SparseMatmul);

REG_OP(SubmSparseConv3dGrad)
    .INPUT(outidx_offset, ge::TensorType::ALL())
    .INPUT(valid_indices, ge::TensorType::ALL())
    .INPUT(grad_out_features, ge::TensorType::ALL())
    .OUTPUT(grad_out_features_iml2col, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(in_channel, Int)
    .OP_END_FACTORY_REG(SubmSparseConv3dGrad);

REG_OP(SubmSparseConv3dGradV2)
    .INPUT(features, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .OPTIONAL_INPUT(grad_out_features, ge::TensorType::ALL())
    .INPUT(indices_offset, ge::TensorType::ALL())
    .OUTPUT(features_grad, ge::TensorType::ALL())
    .OUTPUT(weight_grad, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(SubmSparseConv3dGradV2);

REG_OP(SubmSparseConv3d)
    .INPUT(feature, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .INPUT(temp, ge::TensorType::ALL())
    .OUTPUT(feature_out, ge::TensorType::ALL())
    .OUTPUT(indices_offset, ge::TensorType::ALL())
    .OUTPUT(indices_pair, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(out_channel, Int)
    .REQUIRED_ATTR(outSpatialShape, ListInt)
    .REQUIRED_ATTR(batch_size, Int)
    .OP_END_FACTORY_REG(SubmSparseConv3d);

REG_OP(SubmSparseConv3dV2)
    .INPUT(feature, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .INPUT(map1, ge::TensorType::ALL())
    .INPUT(map2, ge::TensorType::ALL())
    .OUTPUT(feature_out, ge::TensorType::ALL())
    .OUTPUT(indices_offset, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(in_channels, Int)
    .REQUIRED_ATTR(out_spatial_shape, ListInt)
    .REQUIRED_ATTR(batch_size, Int)
    .REQUIRED_ATTR(sparse_rate, Float)
    .OP_END_FACTORY_REG(SubmSparseConv3dV2);

REG_OP(SubmSparseConv3dV3)
    .INPUT(feature, ge::TensorType::ALL())
    .INPUT(weight, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .INPUT(indices_offset, ge::TensorType::ALL())
    .INPUT(map1, ge::TensorType::ALL())
    .INPUT(map2, ge::TensorType::ALL())
    .OUTPUT(feature_out, ge::TensorType::ALL())
    .OUTPUT(out_indices_offset, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(in_channels, Int)
    .REQUIRED_ATTR(out_channels, Int)
    .REQUIRED_ATTR(out_spatial_shape, ListInt)
    .REQUIRED_ATTR(batch_size, Int)
    .REQUIRED_ATTR(with_key, Int)
    .OP_END_FACTORY_REG(SubmSparseConv3dV3);

REG_OP(SubmSparseConv3dWithKey)
    .INPUT(outidx_offset, ge::TensorType::ALL())
    .INPUT(valid_indices, ge::TensorType::ALL())
    .INPUT(grad_out_features, ge::TensorType::ALL())
    .OUTPUT(grad_out_features_iml2col, ge::TensorType::ALL())
    .REQUIRED_ATTR(kernel_size, ListInt)
    .REQUIRED_ATTR(in_channel, Int)
    .OP_END_FACTORY_REG(SubmSparseConv3dWithKey);

REG_OP(UniqueV2)
    .INPUT(input, ge::TensorType::ALL())
    .OUTPUT(output, ge::TensorType::ALL())
    .OUTPUT(uniqueCnt, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(UniqueV2);

REG_OP(UniqueVoxel)
    .INPUT(voxels, ge::TensorType::ALL())
    .INPUT(indices, ge::TensorType::ALL())
    .INPUT(argsort_indices, ge::TensorType::ALL())
    .OUTPUT(uni_voxels, ge::TensorType::ALL())
    .OUTPUT(uni_indices, ge::TensorType::ALL())
    .OUTPUT(uni_argsort_indices, ge::TensorType::ALL())
    .OUTPUT(voxel_num, ge::TensorType::ALL())
    .OP_END_FACTORY_REG(UniqueVoxel);

REG_OP(VoxelPoolingTrain)
    .INPUT(geom, ge::TensorType::ALL())
    .INPUT(input_features, ge::TensorType::ALL())
    .OUTPUT(output_features, ge::TensorType::ALL())
    .OUTPUT(pos_memo, ge::TensorType::ALL())
    .REQUIRED_ATTR(batch_size, Int)
    .REQUIRED_ATTR(num_points, Int)
    .REQUIRED_ATTR(num_channels, Int)
    .REQUIRED_ATTR(num_voxel_x, Int)
    .REQUIRED_ATTR(num_voxel_y, Int)
    .REQUIRED_ATTR(num_voxel_z, Int)
    .OP_END_FACTORY_REG(VoxelPoolingTrain);

REG_OP(VoxelPoolingTrainGrad)
    .INPUT(grad_out, ge::TensorType::ALL())
    .INPUT(pos_memo, ge::TensorType::ALL())
    .OUTPUT(grad_features, ge::TensorType::ALL())
    .REQUIRED_ATTR(batch_size, Int)
    .REQUIRED_ATTR(num_points, Int)
    .REQUIRED_ATTR(num_channels, Int)
    .REQUIRED_ATTR(h, Int)
    .REQUIRED_ATTR(w, Int)
    .OP_END_FACTORY_REG(VoxelPoolingTrainGrad);

}

#endif
